use super::model::{TemplateKind, TemplateSpec};

pub(super) const TEMPLATE_SPECS: &[TemplateSpec] = &[
    TemplateSpec {
        name: "megara.toml",
        kind: TemplateKind::Config,
        relative_path: "megara.toml",
        description: "Megara harness configuration",
        content: include_str!("../../harness/megara.toml"),
    },
    TemplateSpec {
        name: "README.md",
        kind: TemplateKind::Readme,
        relative_path: "README.md",
        description: "Megara harness overview",
        content: include_str!("../../harness/README.md"),
    },
    TemplateSpec {
        name: ".gitignore",
        kind: TemplateKind::ToolSupport,
        relative_path: ".gitignore",
        description: "Megara runtime state ignore rules",
        content: include_str!("../../harness/.gitignore"),
    },
    TemplateSpec {
        name: "planning",
        kind: TemplateKind::Rule,
        relative_path: "rules/planning.md",
        description: "Planning boundary rules",
        content: include_str!("../../harness/rules/planning.md"),
    },
    TemplateSpec {
        name: "deep-interview",
        kind: TemplateKind::Workflow,
        relative_path: "skills/deep-interview/SKILL.md",
        description: "Socratic requirements interview",
        content: include_str!("../../harness/skills/deep-interview/SKILL.md"),
    },
    TemplateSpec {
        name: "ralplan",
        kind: TemplateKind::Workflow,
        relative_path: "skills/ralplan/SKILL.md",
        description: "Consensus planning workflow",
        content: include_str!("../../harness/skills/ralplan/SKILL.md"),
    },
    TemplateSpec {
        name: "ultragoal",
        kind: TemplateKind::Workflow,
        relative_path: "skills/ultragoal/SKILL.md",
        description: "Durable goal execution workflow",
        content: include_str!("../../harness/skills/ultragoal/SKILL.md"),
    },
    TemplateSpec {
        name: "team",
        kind: TemplateKind::Workflow,
        relative_path: "skills/team/SKILL.md",
        description: "Multi-agent lane coordination",
        content: include_str!("../../harness/skills/team/SKILL.md"),
    },
    TemplateSpec {
        name: "caveman",
        kind: TemplateKind::Skill,
        relative_path: "skills/caveman/SKILL.md",
        description: "Always-on terse response compression mode",
        content: include_str!("../../harness/skills/caveman/SKILL.md"),
    },
    TemplateSpec {
        name: "insane-search",
        kind: TemplateKind::Skill,
        relative_path: "skills/insane-search/SKILL.md",
        description: "On-demand skill wrapper for the insane-search tool",
        content: include_str!("../../harness/skills/insane-search/SKILL.md"),
    },
    TemplateSpec {
        name: "insane-search",
        kind: TemplateKind::Tool,
        relative_path: "tools/insane-search/TOOL.md",
        description: "On-demand public web access helper",
        content: include_str!("../../harness/tools/insane-search/TOOL.md"),
    },
    TemplateSpec {
        name: "insane-search/LICENSE",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/LICENSE",
        description: "insane-search license",
        content: include_str!("../../harness/tools/insane-search/LICENSE"),
    },
    TemplateSpec {
        name: "insane-search/requirements.txt",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/requirements.txt",
        description: "insane-search Python dependencies",
        content: include_str!("../../harness/tools/insane-search/requirements.txt"),
    },
    TemplateSpec {
        name: "insane-search/engine/__init__.py",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/engine/__init__.py",
        description: "insane-search engine support",
        content: include_str!("../../harness/tools/insane-search/engine/__init__.py"),
    },
    TemplateSpec {
        name: "insane-search/engine/__main__.py",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/engine/__main__.py",
        description: "insane-search engine CLI",
        content: include_str!("../../harness/tools/insane-search/engine/__main__.py"),
    },
    TemplateSpec {
        name: "insane-search/engine/bias_check.py",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/engine/bias_check.py",
        description: "insane-search bias checker",
        content: include_str!("../../harness/tools/insane-search/engine/bias_check.py"),
    },
    TemplateSpec {
        name: "insane-search/engine/content_safety.py",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/engine/content_safety.py",
        description: "insane-search content safety",
        content: include_str!("../../harness/tools/insane-search/engine/content_safety.py"),
    },
    TemplateSpec {
        name: "insane-search/engine/executor.py",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/engine/executor.py",
        description: "insane-search executor",
        content: include_str!("../../harness/tools/insane-search/engine/executor.py"),
    },
    TemplateSpec {
        name: "insane-search/engine/fetch_chain.py",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/engine/fetch_chain.py",
        description: "insane-search fetch chain",
        content: include_str!("../../harness/tools/insane-search/engine/fetch_chain.py"),
    },
    TemplateSpec {
        name: "insane-search/engine/learning.py",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/engine/learning.py",
        description: "insane-search learning helpers",
        content: include_str!("../../harness/tools/insane-search/engine/learning.py"),
    },
    TemplateSpec {
        name: "insane-search/engine/phase0.py",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/engine/phase0.py",
        description: "insane-search public endpoint router",
        content: include_str!("../../harness/tools/insane-search/engine/phase0.py"),
    },
    TemplateSpec {
        name: "insane-search/engine/safety.py",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/engine/safety.py",
        description: "insane-search URL safety",
        content: include_str!("../../harness/tools/insane-search/engine/safety.py"),
    },
    TemplateSpec {
        name: "insane-search/engine/templates/.gitignore",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/engine/templates/.gitignore",
        description: "insane-search browser template ignore rules",
        content: include_str!("../../harness/tools/insane-search/engine/templates/.gitignore"),
    },
    TemplateSpec {
        name: "insane-search/engine/templates/package.json",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/engine/templates/package.json",
        description: "insane-search browser template dependencies",
        content: include_str!("../../harness/tools/insane-search/engine/templates/package.json"),
    },
    TemplateSpec {
        name: "insane-search/engine/templates/playwright_mobile_chrome.js",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/engine/templates/playwright_mobile_chrome.js",
        description: "insane-search mobile Chrome template",
        content: include_str!(
            "../../harness/tools/insane-search/engine/templates/playwright_mobile_chrome.js"
        ),
    },
    TemplateSpec {
        name: "insane-search/engine/templates/playwright_real_chrome.js",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/engine/templates/playwright_real_chrome.js",
        description: "insane-search real Chrome template",
        content: include_str!(
            "../../harness/tools/insane-search/engine/templates/playwright_real_chrome.js"
        ),
    },
    TemplateSpec {
        name: "insane-search/engine/transport.py",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/engine/transport.py",
        description: "insane-search transport",
        content: include_str!("../../harness/tools/insane-search/engine/transport.py"),
    },
    TemplateSpec {
        name: "insane-search/engine/url_transforms.py",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/engine/url_transforms.py",
        description: "insane-search URL transforms",
        content: include_str!("../../harness/tools/insane-search/engine/url_transforms.py"),
    },
    TemplateSpec {
        name: "insane-search/engine/validators.py",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/engine/validators.py",
        description: "insane-search validators",
        content: include_str!("../../harness/tools/insane-search/engine/validators.py"),
    },
    TemplateSpec {
        name: "insane-search/engine/waf_detector.py",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/engine/waf_detector.py",
        description: "insane-search WAF detector",
        content: include_str!("../../harness/tools/insane-search/engine/waf_detector.py"),
    },
    TemplateSpec {
        name: "insane-search/engine/waf_profiles.yaml",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/engine/waf_profiles.yaml",
        description: "insane-search WAF profiles",
        content: include_str!("../../harness/tools/insane-search/engine/waf_profiles.yaml"),
    },
    TemplateSpec {
        name: "insane-search/references/cache-archive",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/references/cache-archive.md",
        description: "insane-search cache and archive reference",
        content: include_str!("../../harness/tools/insane-search/references/cache-archive.md"),
    },
    TemplateSpec {
        name: "insane-search/references/fallback",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/references/fallback.md",
        description: "insane-search fallback reference",
        content: include_str!("../../harness/tools/insane-search/references/fallback.md"),
    },
    TemplateSpec {
        name: "insane-search/references/jina",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/references/jina.md",
        description: "insane-search Jina reference",
        content: include_str!("../../harness/tools/insane-search/references/jina.md"),
    },
    TemplateSpec {
        name: "insane-search/references/json-api",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/references/json-api.md",
        description: "insane-search JSON API reference",
        content: include_str!("../../harness/tools/insane-search/references/json-api.md"),
    },
    TemplateSpec {
        name: "insane-search/references/media",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/references/media.md",
        description: "insane-search media reference",
        content: include_str!("../../harness/tools/insane-search/references/media.md"),
    },
    TemplateSpec {
        name: "insane-search/references/metadata",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/references/metadata.md",
        description: "insane-search metadata reference",
        content: include_str!("../../harness/tools/insane-search/references/metadata.md"),
    },
    TemplateSpec {
        name: "insane-search/references/naver",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/references/naver.md",
        description: "insane-search Naver reference",
        content: include_str!("../../harness/tools/insane-search/references/naver.md"),
    },
    TemplateSpec {
        name: "insane-search/references/playwright",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/references/playwright.md",
        description: "insane-search Playwright reference",
        content: include_str!("../../harness/tools/insane-search/references/playwright.md"),
    },
    TemplateSpec {
        name: "insane-search/references/public-api",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/references/public-api.md",
        description: "insane-search public API reference",
        content: include_str!("../../harness/tools/insane-search/references/public-api.md"),
    },
    TemplateSpec {
        name: "insane-search/references/rss",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/references/rss.md",
        description: "insane-search RSS reference",
        content: include_str!("../../harness/tools/insane-search/references/rss.md"),
    },
    TemplateSpec {
        name: "insane-search/references/tls-impersonate",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/references/tls-impersonate.md",
        description: "insane-search TLS impersonation reference",
        content: include_str!("../../harness/tools/insane-search/references/tls-impersonate.md"),
    },
    TemplateSpec {
        name: "insane-search/references/twitter",
        kind: TemplateKind::ToolSupport,
        relative_path: "tools/insane-search/references/twitter.md",
        description: "insane-search Twitter reference",
        content: include_str!("../../harness/tools/insane-search/references/twitter.md"),
    },
    TemplateSpec {
        name: "deep-interview/auto-answer-uncertain",
        kind: TemplateKind::SkillFragment,
        relative_path: "skill-fragments/deep-interview/auto-answer-uncertain.md",
        description: "Deep Interview uncertain-answer fragment",
        content: include_str!(
            "../../harness/skill-fragments/deep-interview/auto-answer-uncertain.md"
        ),
    },
    TemplateSpec {
        name: "deep-interview/auto-research-greenfield",
        kind: TemplateKind::SkillFragment,
        relative_path: "skill-fragments/deep-interview/auto-research-greenfield.md",
        description: "Deep Interview greenfield research fragment",
        content: include_str!(
            "../../harness/skill-fragments/deep-interview/auto-research-greenfield.md"
        ),
    },
    TemplateSpec {
        name: "deep-interview/lateral-review-panel",
        kind: TemplateKind::SkillFragment,
        relative_path: "skill-fragments/deep-interview/lateral-review-panel.md",
        description: "Deep Interview lateral review fragment",
        content: include_str!(
            "../../harness/skill-fragments/deep-interview/lateral-review-panel.md"
        ),
    },
    TemplateSpec {
        name: "ultragoal/ai-slop-cleaner",
        kind: TemplateKind::SkillFragment,
        relative_path: "skill-fragments/ultragoal/ai-slop-cleaner.md",
        description: "Ultragoal cleanup detector fragment",
        content: include_str!("../../harness/skill-fragments/ultragoal/ai-slop-cleaner.md"),
    },
    TemplateSpec {
        name: "executor",
        kind: TemplateKind::Agent,
        relative_path: "agents/executor.toml",
        description: "Implementation agent",
        content: include_str!("../../harness/agents/executor.toml"),
    },
    TemplateSpec {
        name: "planner",
        kind: TemplateKind::Agent,
        relative_path: "agents/planner.toml",
        description: "Planning agent",
        content: include_str!("../../harness/agents/planner.toml"),
    },
    TemplateSpec {
        name: "architect",
        kind: TemplateKind::Agent,
        relative_path: "agents/architect.toml",
        description: "Architecture review agent",
        content: include_str!("../../harness/agents/architect.toml"),
    },
    TemplateSpec {
        name: "critic",
        kind: TemplateKind::Agent,
        relative_path: "agents/critic.toml",
        description: "Plan critic agent",
        content: include_str!("../../harness/agents/critic.toml"),
    },
    TemplateSpec {
        name: "researcher",
        kind: TemplateKind::Agent,
        relative_path: "agents/researcher.toml",
        description: "Evidence research agent",
        content: include_str!("../../harness/agents/researcher.toml"),
    },
    TemplateSpec {
        name: "contrarian",
        kind: TemplateKind::Agent,
        relative_path: "agents/contrarian.toml",
        description: "Adversarial review agent",
        content: include_str!("../../harness/agents/contrarian.toml"),
    },
    TemplateSpec {
        name: "simplifier",
        kind: TemplateKind::Agent,
        relative_path: "agents/simplifier.toml",
        description: "Scope simplification agent",
        content: include_str!("../../harness/agents/simplifier.toml"),
    },
    TemplateSpec {
        name: "pi-extension",
        kind: TemplateKind::ToolSupport,
        relative_path: "pi/extensions/megara.ts",
        description: "Pi Coding Agent runtime extension",
        content: include_str!("../../harness/pi/extensions/megara.ts"),
    },
];
