use std::path::Path;

pub const MANAGED_MARKER: &str = "MEGARA:MANAGED";

pub(super) fn add_marker(path: &Path, content: String) -> String {
    let extension = path.extension().and_then(|extension| extension.to_str());
    let file_name = path.file_name().and_then(|file_name| file_name.to_str());

    if extension.is_some_and(|extension| extension == "json") {
        content
    } else if extension.is_some_and(|extension| extension == "sh") {
        add_shell_marker(content)
    } else if extension.is_some_and(|extension| matches!(extension, "toml" | "py" | "yaml" | "yml"))
        || file_name.is_some_and(|file_name| matches!(file_name, ".gitignore" | "requirements.txt"))
    {
        line_marker(content)
    } else if extension.is_some_and(|extension| matches!(extension, "js" | "mjs" | "ts")) {
        slash_marker(content)
    } else {
        html_marker(content)
    }
}

pub fn strip_managed_marker(content: &str) -> String {
    let mut stripped = String::new();
    for line in content.split_inclusive('\n') {
        if !line.contains(MANAGED_MARKER) {
            stripped.push_str(line);
        }
    }
    stripped
}

pub(super) fn add_shell_marker(content: String) -> String {
    if let Some(stripped) = content.strip_prefix("#!") {
        if let Some(shebang_end) = stripped.find('\n') {
            let split_at = 2 + shebang_end + 1;
            return format!(
                "{}# {MANAGED_MARKER} generated by Megara. Edit SSOT and run `megara sync`.\n{}",
                &content[..split_at],
                &content[split_at..]
            );
        }
    }
    line_marker(content)
}

fn line_marker(content: String) -> String {
    format!("# {MANAGED_MARKER} generated by Megara. Edit SSOT and run `megara sync`.\n{content}")
}

fn slash_marker(content: String) -> String {
    format!("// {MANAGED_MARKER} generated by Megara. Edit SSOT and run `megara sync`.\n{content}")
}

fn html_marker(content: String) -> String {
    if let Some(stripped) = content.strip_prefix("---\n") {
        if let Some(frontmatter_end) = stripped.find("\n---\n") {
            let split_at = 4 + frontmatter_end + "\n---\n".len();
            return format!(
                "{}<!-- {MANAGED_MARKER} generated by Megara. Edit SSOT and run `megara sync`. -->\n{}",
                &content[..split_at],
                &content[split_at..]
            );
        }
    }
    format!(
        "<!-- {MANAGED_MARKER} generated by Megara. Edit SSOT and run `megara sync`. -->\n{content}"
    )
}
