use anyhow::Result;

use crate::templates::TemplateRegistry;

use super::config::HarnessConfig;

pub(super) fn codex_agents_md(registry: &TemplateRegistry) -> Result<String> {
    let config = HarnessConfig::from_registry(registry)?;
    let workflows = registry
        .workflows()
        .iter()
        .map(|workflow| format!("- `{}`", workflow.name))
        .collect::<Vec<_>>()
        .join("\n");
    let skills = registry
        .skills()
        .iter()
        .map(|skill| format!("- `{}`", skill.name))
        .collect::<Vec<_>>()
        .join("\n");
    let default_active_skills = if config.default_active_skills.is_empty() {
        "- none".to_string()
    } else {
        config
            .default_active_skills
            .iter()
            .map(|skill| format!("- `{skill}`"))
            .collect::<Vec<_>>()
            .join("\n")
    };
    let fragments = registry
        .fragments()
        .iter()
        .map(|fragment| format!("- `{}`", fragment.name))
        .collect::<Vec<_>>()
        .join("\n");
    let tools = registry
        .tools()
        .iter()
        .map(|tool| {
            format!(
                "- `{}`: read `{}` only when needed",
                tool.name, tool.relative_path
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    let agents = registry
        .agents()
        .iter()
        .map(|agent| format!("- `{}`", agent.name))
        .collect::<Vec<_>>()
        .join("\n");

    Ok(format!(
        r#"# Megara Codex Harness

This file is generated by Megara. Edit the Megara SSOT, then run `megara sync`.

## Locale

- Locale: `{}`.
- Write user-facing prose in the configured locale unless the user explicitly requests another language.
- The locale rule applies to progress updates, clarification questions, option labels, assumptions, plans, status reports, and final answers.
- Keep code identifiers, file paths, commands, config keys, package names, API names, and quoted source text unchanged.
- Do not mix languages in explanatory prose. If technical literals are English, explain around them in the configured locale.
- Before sending a user-facing response, rewrite stock English workflow phrases into the configured locale. Do not leave English lead-ins such as "Next", "I will", "Done", or "Unit suite is green" in prose when the configured locale is not English.
- Do not copy English workflow headings into visible prose. Translate labels such as "Round 0: Topology Confirmation", "remaining ambiguity", "weakest dimension", and "next target" into the configured locale.
- Structured Megara block keys must stay parseable, but free-text values such as `question`, `options`, `rationale`, and `summary` should use the configured locale unless they are technical literals.

## Workflows

{workflows}

## Skills

{skills}

## Default Active Skills

{default_active_skills}

- Runtime adapters may reinforce default active skills at session start when hook support is available.
- If `caveman` is active and the user asks for `normal mode` or `stop caveman`, stop compressing prose.

## Internal Fragments

{fragments}

## On-Demand Tools

{tools}

- On-demand tools are not default active skills.
- Use them only when the user's request or a failed lightweight route needs that tool.
- Project scope stores tool files under `.agents/tools`; global scope stores them under `~/.megara/tools`.
- Prefer `.agents/bin/<tool-name>` in project scope and `~/.megara/bin/<tool-name>` in global scope when a wrapper exists.

## Hooks

- Codex hooks call the Megara executable path captured at install time.
- Hook output and Megara CLI state are runtime internals. Do not expose session ids, handoff files, state paths, checkpoints, receipts, quality-gate JSON, hook event names, or workflow metadata in user-facing prose unless the user explicitly asks to debug Megara itself.
- Runtime artifact paths under `.megara/state`, `.megara/artifacts`, `~/.megara/state`, or `~/.megara/artifacts` are internal-only. Do not link them, cite them as deliverables, list them as changed files, or include them in final summaries; translate them into product-facing verification notes.
- When a workflow command is required, run it silently and translate the result into product-level progress, blockers, verification, or completion.

## Codex Runtime Adapter

- This projected harness is running inside Codex.
- Deep-interview does not require Codex Plan mode.
- Do not ask the user to toggle `/plan`, resend the same workflow request in Plan mode, or choose a fallback path because of Plan mode.
- Codex App delegated prompts may arrive wrapped as `<codex_delegation><input>...</input>`; Megara hooks use the effective prompt inside `<input>` for workflow state.
- After `deep-interview` crystallizes, the next workflow must be `ralplan`; implementation mutation is blocked until `ralplan` owns or approves the handoff.
- Workflow start hooks may add hidden developer context that requires specific context-only, tool-free subagents. `SubagentStart` and `SubagentStop` are observed as runtime events, and terminal workflow responses may be continued until the required receipts exist. Do not make a subagent own the user-facing interview loop or final approval wording.

## Agents

{agents}

## Rules

- Clarify ambiguity before implementation.
- Keep implementation scoped to the accepted plan.
- Verify behavior before final response.
"#,
        config.locale
    ))
}
