use anyhow::Result;

use crate::templates::TemplateRegistry;

use super::config::HarnessConfig;

pub(super) fn codex_agents_md(registry: &TemplateRegistry) -> Result<String> {
    let config = HarnessConfig::from_registry(registry)?;
    let workflows = registry
        .workflows()
        .iter()
        .map(|workflow| format!("- `{}`", workflow.name))
        .collect::<Vec<_>>()
        .join("\n");
    let fragments = registry
        .fragments()
        .iter()
        .map(|fragment| format!("- `{}`", fragment.name))
        .collect::<Vec<_>>()
        .join("\n");
    let agents = registry
        .agents()
        .iter()
        .map(|agent| format!("- `{}`", agent.name))
        .collect::<Vec<_>>()
        .join("\n");

    Ok(format!(
        r#"# Megara Codex Harness

This file is generated by Megara. Edit the Megara SSOT, then run `megara sync`.

## Locale

- Locale: `{}`.
- Write user-facing prose in the configured locale unless the user explicitly requests another language.
- The locale rule applies to progress updates, clarification questions, option labels, assumptions, plans, status reports, and final answers.
- Keep code identifiers, file paths, commands, config keys, package names, API names, and quoted source text unchanged.
- Do not mix languages in explanatory prose. If technical literals are English, explain around them in the configured locale.
- Before sending a user-facing response, rewrite stock English workflow phrases into the configured locale. Do not leave English lead-ins such as "Next", "I will", "Done", or "Unit suite is green" in prose when the configured locale is not English.
- Do not copy English workflow headings into visible prose. Translate labels such as "Round 0: Topology Confirmation", "remaining ambiguity", "weakest dimension", and "next target" into the configured locale.
- Structured Megara block keys must stay parseable, but free-text values such as `question`, `options`, `rationale`, and `summary` should use the configured locale unless they are technical literals.

## Workflows

{workflows}

## Internal Fragments

{fragments}

## Hooks

- Codex hooks call the Megara executable path captured at install time.

## Agents

{agents}

## Rules

- Clarify ambiguity before implementation.
- Keep implementation scoped to the accepted plan.
- Verify behavior before final response.
"#,
        config.locale
    ))
}
