use std::path::PathBuf;

use crate::{
    installer::PlannedFile,
    templates::{HarnessTemplate, TemplateRegistry},
};

pub fn projection_files(root: PathBuf, registry: &TemplateRegistry) -> Vec<PlannedFile> {
    let mut files = Vec::new();
    files.push(PlannedFile::new(
        root.join("AGENTS.md"),
        codex_agents_md(registry),
    ));
    files.push(PlannedFile::new(root.join("config.toml"), codex_config()));
    files.push(PlannedFile::new(
        root.join("hooks.json"),
        codex_hooks_json(),
    ));

    for workflow in registry.workflows() {
        files.push(PlannedFile::new(
            root.join("skills").join(&workflow.name).join("SKILL.md"),
            workflow.content.clone(),
        ));
    }

    for fragment in registry.fragments() {
        files.push(PlannedFile::new(
            root.join(&fragment.relative_path),
            fragment.content.clone(),
        ));
    }

    for hook in registry.hooks() {
        files.push(PlannedFile::new(
            root.join(&hook.relative_path),
            hook.content.clone(),
        ));
    }

    for agent in registry.agents() {
        files.push(PlannedFile::new(
            root.join("agents").join(format!("{}.toml", agent.name)),
            agent_toml(agent),
        ));
    }

    files
}

fn codex_agents_md(registry: &TemplateRegistry) -> String {
    let workflows = registry
        .workflows()
        .iter()
        .map(|workflow| format!("- `{}`", workflow.name))
        .collect::<Vec<_>>()
        .join("\n");
    let fragments = registry
        .fragments()
        .iter()
        .map(|fragment| format!("- `{}`", fragment.name))
        .collect::<Vec<_>>()
        .join("\n");
    let hooks = registry
        .hooks()
        .iter()
        .map(|hook| format!("- `{}`", hook.relative_path))
        .collect::<Vec<_>>()
        .join("\n");
    let agents = registry
        .agents()
        .iter()
        .map(|agent| format!("- `{}`", agent.name))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"# Megara Codex Harness

This file is generated by Megara. Edit the Megara SSOT, then run `megara sync`.

## Workflows

{workflows}

## Internal Fragments

{fragments}

## Hooks

{hooks}

## Agents

{agents}

## Rules

- Clarify ambiguity before implementation.
- Keep implementation scoped to the accepted plan.
- Verify behavior before final response.
"#
    )
}

fn codex_config() -> String {
    r#"# Megara Codex projection.
# Codex discovers skills, agents, and hooks from this directory.
"#
    .to_string()
}

fn codex_hooks_json() -> String {
    r#"{
  "hooks": {
    "UserPromptSubmit": [
      {
        "hooks": [
          {
            "name": "megara-hook-UserPromptSubmit",
            "type": "command",
            "command": "MEGARA_MANAGED='MEGARA:MANAGED' sh '.codex/hooks/megara-hook.sh' --runtime 'codex' --event 'UserPromptSubmit'",
            "timeout": 21
          }
        ]
      }
    ],
    "PreToolUse": [
      {
        "hooks": [
          {
            "name": "megara-hook-PreToolUse",
            "type": "command",
            "command": "MEGARA_MANAGED='MEGARA:MANAGED' sh '.codex/hooks/megara-hook.sh' --runtime 'codex' --event 'PreToolUse' --matcher 'Bash'",
            "timeout": 10
          }
        ],
        "matcher": "Bash"
      }
    ],
    "Stop": [
      {
        "hooks": [
          {
            "name": "megara-hook-Stop",
            "type": "command",
            "command": "MEGARA_MANAGED='MEGARA:MANAGED' sh '.codex/hooks/megara-hook.sh' --runtime 'codex' --event 'Stop'",
            "timeout": 10
          }
        ]
      }
    ]
  }
}
"#
    .to_string()
}

fn agent_toml(template: &HarnessTemplate) -> String {
    format!(
        r#"name = "{}"
description = "{}"

instructions = '''
{}
'''
"#,
        template.name, template.description, template.content
    )
}
