use std::path::PathBuf;

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

use crate::{
    installer::PlannedFile,
    templates::{HarnessTemplate, TemplateRegistry},
};

const DEFAULT_LOCALE: &str = "ko-KR";

pub fn projection_files(root: PathBuf, registry: &TemplateRegistry) -> Result<Vec<PlannedFile>> {
    let mut files = Vec::new();
    files.push(PlannedFile::new(
        root.join("AGENTS.md"),
        codex_agents_md(registry)?,
    ));
    files.push(PlannedFile::new(root.join("config.toml"), codex_config()));
    files.push(PlannedFile::new(
        root.join("hooks.json"),
        codex_hooks_json(),
    ));

    for workflow in registry.workflows() {
        files.push(PlannedFile::new(
            root.join("skills").join(&workflow.name).join("SKILL.md"),
            workflow.content.clone(),
        ));
    }

    for fragment in registry.fragments() {
        files.push(PlannedFile::new(
            root.join(&fragment.relative_path),
            fragment.content.clone(),
        ));
    }

    for hook in registry.hooks() {
        files.push(PlannedFile::new(
            root.join(&hook.relative_path),
            hook.content.clone(),
        ));
    }

    for agent in registry.agents() {
        let (agent_id, agent_content) = agent_toml(agent)?;
        files.push(PlannedFile::new(
            root.join("agents").join(format!("{agent_id}.toml")),
            agent_content,
        ));
    }

    Ok(files)
}

fn codex_agents_md(registry: &TemplateRegistry) -> Result<String> {
    let config = HarnessConfig::from_registry(registry)?;
    let workflows = registry
        .workflows()
        .iter()
        .map(|workflow| format!("- `{}`", workflow.name))
        .collect::<Vec<_>>()
        .join("\n");
    let fragments = registry
        .fragments()
        .iter()
        .map(|fragment| format!("- `{}`", fragment.name))
        .collect::<Vec<_>>()
        .join("\n");
    let hooks = registry
        .hooks()
        .iter()
        .map(|hook| format!("- `{}`", hook.relative_path))
        .collect::<Vec<_>>()
        .join("\n");
    let agents = registry
        .agents()
        .iter()
        .map(|agent| format!("- `{}`", agent.name))
        .collect::<Vec<_>>()
        .join("\n");

    Ok(format!(
        r#"# Megara Codex Harness

This file is generated by Megara. Edit the Megara SSOT, then run `megara sync`.

## Locale

- Locale: `{}`.
- Write user-facing prose in the configured locale unless the user explicitly requests another language.
- The locale rule applies to progress updates, clarification questions, option labels, assumptions, plans, status reports, and final answers.
- Keep code identifiers, file paths, commands, config keys, package names, API names, and quoted source text unchanged.
- Do not mix languages in explanatory prose. If technical literals are English, explain around them in the configured locale.
- Before sending a user-facing response, rewrite stock English workflow phrases into the configured locale. Do not leave English lead-ins such as "Next", "I will", "Done", or "Unit suite is green" in prose when the configured locale is not English.
- Structured Megara block keys must stay parseable, but free-text values such as `question`, `options`, `rationale`, and `summary` should use the configured locale unless they are technical literals.

## Workflows

{workflows}

## Internal Fragments

{fragments}

## Hooks

{hooks}

## Agents

{agents}

## Rules

- Clarify ambiguity before implementation.
- Keep implementation scoped to the accepted plan.
- Verify behavior before final response.
"#,
        config.locale
    ))
}

fn codex_config() -> String {
    r#"# Megara Codex projection.
# Codex discovers skills, agents, and hooks from this directory.
"#
    .to_string()
}

fn codex_hooks_json() -> String {
    r#"{
  "hooks": {
    "UserPromptSubmit": [
      {
        "hooks": [
          {
            "name": "megara-hook-UserPromptSubmit",
            "type": "command",
            "command": "MEGARA_MANAGED='MEGARA:MANAGED' sh '.codex/hooks/megara-hook.sh' --runtime 'codex' --event 'UserPromptSubmit'",
            "timeout": 21
          }
        ]
      }
    ],
    "PreToolUse": [
      {
        "hooks": [
          {
            "name": "megara-hook-PreToolUse",
            "type": "command",
            "command": "MEGARA_MANAGED='MEGARA:MANAGED' sh '.codex/hooks/megara-hook.sh' --runtime 'codex' --event 'PreToolUse' --matcher 'Bash'",
            "timeout": 10
          }
        ],
        "matcher": "Bash"
      }
    ],
    "Stop": [
      {
        "hooks": [
          {
            "name": "megara-hook-Stop",
            "type": "command",
            "command": "MEGARA_MANAGED='MEGARA:MANAGED' sh '.codex/hooks/megara-hook.sh' --runtime 'codex' --event 'Stop'",
            "timeout": 10
          }
        ]
      }
    ]
  }
}
"#
    .to_string()
}

#[derive(Debug, Deserialize)]
struct AgentSpec {
    id: String,
    name: String,
    description: String,
    instructions: String,
}

#[derive(Debug, Serialize)]
struct CodexAgentSpec<'a> {
    name: &'a str,
    description: &'a str,
    developer_instructions: &'a str,
}

fn agent_toml(template: &HarnessTemplate) -> Result<(String, String)> {
    let agent: AgentSpec = toml::from_str(&template.content)
        .with_context(|| format!("failed to parse agent SSOT {}", template.relative_path))?;
    let codex_agent = CodexAgentSpec {
        name: &agent.name,
        description: &agent.description,
        developer_instructions: &agent.instructions,
    };
    let content = toml::to_string_pretty(&codex_agent)
        .with_context(|| format!("failed to render Codex agent {}", agent.id))?;
    Ok((agent.id, content))
}

#[derive(Debug, Deserialize)]
struct HarnessConfig {
    #[serde(default = "default_locale")]
    locale: String,
}

fn default_locale() -> String {
    DEFAULT_LOCALE.to_string()
}

impl HarnessConfig {
    fn from_registry(registry: &TemplateRegistry) -> Result<Self> {
        let Some(template) = registry.config() else {
            return Ok(Self {
                locale: default_locale(),
            });
        };
        let mut config: Self = toml::from_str(&template.content)
            .with_context(|| format!("failed to parse config SSOT {}", template.relative_path))?;
        if config.locale.trim().is_empty() {
            config.locale = default_locale();
        }
        Ok(config)
    }
}
