use serde_json::Value;
use sha2::{Digest, Sha256};

const SKILL_HASHES: &[(&str, &str)] = &[
    (
        "deep-interview/SKILL.md",
        "3e83b4a4410defe3175e1ccc1275c54301f303fcc03b1c3f8ca9ba097a42ad0c",
    ),
    (
        "ralplan/SKILL.md",
        "dccbe98d696adc2c9c19f10e642113b4806f5eaa10ca6395ebcbb762f382e749",
    ),
    (
        "team/SKILL.md",
        "4930278582a90133e5d16c8155eee53c66aa8796012a87a736fa90b0ef24fd58",
    ),
    (
        "ultragoal/SKILL.md",
        "7cf1f1110b6710de56eae7d93d2e9d7d6eea0bad78f17d00005098e0c4fa2337",
    ),
];

const FRAGMENT_HASHES: &[(&str, &str)] = &[
    (
        "deep-interview/auto-answer-uncertain.md",
        "4ca53fb6942b8d06bf17ef042e1d11ba214b024b7f76f92b433ee05c9d093d82",
    ),
    (
        "deep-interview/auto-research-greenfield.md",
        "fcaf78df91e57c406fbc6d4e1a4236429f95c7c1b888609e06fe1bbe0bd5e6df",
    ),
    (
        "deep-interview/lateral-review-panel.md",
        "2e2117a6fc234f5e78561fd83b7dc114d946e5d3379a9b027fa0bfc7686dff27",
    ),
    (
        "ultragoal/ai-slop-cleaner.md",
        "e0682e30281e08fcfb18a89d89fae9c398d1ac291e61de00c2dc8bd91efb25c5",
    ),
];

pub(crate) fn is_exact_legacy(path: &str, bytes: &[u8]) -> bool {
    if path == ".codex/hooks.json" {
        return normalized_hooks_match(bytes);
    }
    let eligible = path.starts_with(".agents/skills/")
        || path.starts_with(".codex/skills/")
        || path.starts_with(".agents/skill-fragments/")
        || path.starts_with(".codex/skill-fragments/");
    if !eligible {
        return false;
    }
    let Some(template) = path
        .split_once("/skills/")
        .map(|(_, value)| value)
        .or_else(|| path.split_once("/skill-fragments/").map(|(_, value)| value))
    else {
        return false;
    };
    let expected = SKILL_HASHES
        .iter()
        .chain(FRAGMENT_HASHES.iter())
        .find_map(|(name, hash)| (*name == template).then_some(*hash));
    expected.is_some_and(|expected| sha256(&strip_one_marker(bytes)) == expected)
}

fn strip_one_marker(bytes: &[u8]) -> Vec<u8> {
    let Ok(text) = std::str::from_utf8(bytes) else {
        return bytes.to_vec();
    };
    let marker = "<!-- MEGARA:MANAGED generated by Megara. Edit SSOT and run `megara sync`. -->";
    if text.matches("MEGARA:MANAGED").count() != 1 {
        return bytes.to_vec();
    }
    let marker_line = format!("{marker}\n");
    let marker_at = if text.starts_with(&marker_line) {
        Some(0)
    } else if text.starts_with("---\n") {
        text.find("\n---\n")
            .map(|index| index + "\n---\n".len())
            .filter(|index| text[*index..].starts_with(&marker_line))
    } else {
        None
    };
    let Some(index) = marker_at else {
        return bytes.to_vec();
    };
    let mut output = String::with_capacity(text.len() - marker_line.len());
    output.push_str(&text[..index]);
    output.push_str(&text[index + marker_line.len()..]);
    output.into_bytes()
}

fn sha256(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    format!("{:x}", hasher.finalize())
}

fn normalized_hooks_match(bytes: &[u8]) -> bool {
    let Ok(value) = serde_json::from_slice::<Value>(bytes) else {
        return false;
    };
    let Some(root) = value.as_object() else {
        return false;
    };
    if root.len() != 1 || !root.contains_key("hooks") {
        return false;
    }
    let Some(hooks) = root.get("hooks").and_then(Value::as_object) else {
        return false;
    };
    let expected = [
        "SessionStart",
        "UserPromptSubmit",
        "PreToolUse",
        "PostToolUse",
        "Stop",
        "SubagentStart",
        "SubagentStop",
    ];
    hooks.len() == expected.len()
        && expected.iter().all(|event| {
            hooks
                .get(*event)
                .is_some_and(|groups| normalized_event(event, groups))
        })
}

fn normalized_event(event: &str, value: &Value) -> bool {
    let Some(groups) = value.as_array() else {
        return false;
    };
    if groups.len() != 1 {
        return false;
    }
    let Some(group) = groups[0].as_object() else {
        return false;
    };
    let Some(handlers) = group.get("hooks").and_then(Value::as_array) else {
        return false;
    };
    if handlers.len() != 1 {
        return false;
    }
    if event == "SessionStart" {
        if group.len() != 2
            || group.get("matcher").and_then(Value::as_str) != Some("startup|resume")
        {
            return false;
        }
    } else if group.len() != 1 {
        return false;
    }
    let Some(handler) = handlers[0].as_object() else {
        return false;
    };
    let expected_name = if event == "SessionStart" {
        "megara-caveman-SessionStart".to_string()
    } else {
        format!("megara-hook-{event}")
    };
    if handler.get("name").and_then(Value::as_str) != Some(expected_name.as_str())
        || handler.get("type").and_then(Value::as_str) != Some("command")
    {
        return false;
    }
    let Some(command) = handler.get("command").and_then(Value::as_str) else {
        return false;
    };
    let timeout = handler.get("timeout").and_then(Value::as_u64);
    if event == "SessionStart" {
        handler.len() == 5
            && timeout == Some(5)
            && handler.get("matcher").is_none()
            && handler.get("statusMessage").and_then(Value::as_str) == Some("Loading caveman mode")
            && command == caveman_command()
    } else {
        handler.len() == 4
            && timeout == Some(if event == "UserPromptSubmit" { 21 } else { 10 })
            && normalized_hook_command(command, event)
    }
}

fn normalized_hook_command(command: &str, event: &str) -> bool {
    let Some((binary, rest)) = command.split_once(" hook --managed-marker MEGARA:MANAGED --scope ")
    else {
        return false;
    };
    if binary.is_empty()
        || !binary.starts_with('"')
        || !binary.ends_with('"')
        || binary[1..binary.len() - 1].contains('"')
    {
        return false;
    }
    if let Some(project_and_event) = rest.strip_prefix("project --project-root \"") {
        let Some((project, suffix)) = project_and_event.split_once("\" --runtime codex --event ")
        else {
            return false;
        };
        !project.is_empty() && !project.contains('"') && suffix == event
    } else if let Some(suffix) = rest.strip_prefix("global --runtime codex --event ") {
        suffix == event
    } else {
        false
    }
}

fn caveman_command() -> &'static str {
    "echo 'CAVEMAN MODE ACTIVE. Rules: Drop articles/filler/pleasantries/hedging. Fragments OK. Short synonyms. Pattern: [thing] [action] [reason]. [next step]. Off only: stop caveman / normal mode. Code, commands, commits, PRs: write normal.'"
}
