use std::{fs, path::PathBuf};

use anyhow::{bail, Context, Result};
use serde::{Deserialize, Serialize};
use toml::Value;

use crate::{
    cli::{AgentsArgs, AgentsCommands, ConfigureAgentsArgs, ResetAgentsArgs, ShowAgentsArgs},
    installer::{strip_managed_marker, InstallAction, InstallOptions, Planner},
    paths::{home_dir, InstallScope, TargetRuntime},
    templates::TemplateRegistry,
    tui,
    ui::{self, Section},
};

const CONFIG_MARKER: &str =
    "# MEGARA:MANAGED generated by Megara. Edit SSOT and run `megara sync`.\n";

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct RolePolicy {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_effort: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thinking_level: Option<String>,
}

impl RolePolicy {
    pub fn merge(&mut self, override_policy: Self) {
        if override_policy.model.is_some() {
            self.model = override_policy.model;
        }
        if override_policy.reasoning_effort.is_some() {
            self.reasoning_effort = override_policy.reasoning_effort;
        }
        if override_policy.thinking_level.is_some() {
            self.thinking_level = override_policy.thinking_level;
        }
    }
}

pub fn config_path(scope: InstallScope) -> Result<PathBuf> {
    match scope {
        InstallScope::Project => Ok(std::env::current_dir()?.join(".agents/megara.toml")),
        InstallScope::Global => Ok(home_dir()?.join(".megara/megara.toml")),
    }
}

pub fn effective_policy(
    scope: InstallScope,
    target: TargetRuntime,
    role: &str,
    local_config: &str,
) -> Result<RolePolicy> {
    let mut policy = RolePolicy::default();
    if scope == InstallScope::Project {
        if let Some(global) = read_config(InstallScope::Global)? {
            policy.merge(policy_from_config(&global, target, role)?);
        }
    }
    policy.merge(policy_from_config(local_config, target, role)?);
    Ok(policy)
}

pub fn run(args: AgentsArgs, registry: &TemplateRegistry) -> Result<()> {
    match args.command {
        AgentsCommands::Configure(args) => configure_and_sync(args, registry),
        AgentsCommands::Show(args) => show(args, registry),
        AgentsCommands::Reset(args) => reset_and_sync(args, registry),
    }
}

fn configure_and_sync(args: ConfigureAgentsArgs, registry: &TemplateRegistry) -> Result<()> {
    let roles_for_wizard = registry
        .agents()
        .into_iter()
        .map(|agent| agent.name.clone())
        .collect::<Vec<_>>();
    let needs_wizard = args.scope.is_none()
        || args.target.is_none()
        || (args.role.is_empty() && !args.all)
        || args.model.is_none()
        || (matches!(args.target, Some(crate::cli::TargetArg::Codex))
            && args.reasoning_effort.is_none())
        || (matches!(args.target, Some(crate::cli::TargetArg::Pi))
            && args.thinking_level.is_none());
    let args = if needs_wizard {
        if !tui::interactive_terminal() {
            bail!(
                "megara agents configure needs --scope, --target, --role, --model, and the runtime reasoning level in non-interactive mode"
            );
        }
        let Some(args) = tui::configure_agents_wizard(args, &roles_for_wizard)? else {
            return Ok(());
        };
        args
    } else {
        args
    };
    let scope: InstallScope = args.scope.expect("wizard resolves scope").into();
    let target: TargetRuntime = args.target.expect("wizard resolves target").into();
    let roles = selected_roles(&args.role, args.all, registry)?;
    let policy = RolePolicy {
        model: args.model,
        reasoning_effort: args.reasoning_effort,
        thinking_level: args.thinking_level,
    };
    if policy.model.is_none()
        && policy.reasoning_effort.is_none()
        && policy.thinking_level.is_none()
    {
        bail!("configure requires --model, --reasoning-effort, or --thinking-level");
    }
    configure(scope, target, &roles, policy, args.force)?;
    reproject(scope, target, registry)?;
    print_change("configured", scope, target, &roles, args.json)
}

fn reset_and_sync(args: ResetAgentsArgs, registry: &TemplateRegistry) -> Result<()> {
    let scope: InstallScope = args.scope.into();
    let target: TargetRuntime = args.target.into();
    let roles = selected_roles(&args.role, args.all, registry)?;
    reset(scope, target, &roles, args.force)?;
    reproject(scope, target, registry)?;
    print_change("reset", scope, target, &roles, args.json)
}

fn show(args: ShowAgentsArgs, registry: &TemplateRegistry) -> Result<()> {
    let scope: InstallScope = args.scope.into();
    let target: TargetRuntime = args.target.into();
    let roles = selected_roles(&args.role, args.role.is_empty(), registry)?;
    let config =
        read_config(scope)?.context("Megara harness is not installed; run megara install first")?;
    let rows = roles
        .iter()
        .map(|role| {
            let policy = effective_policy(scope, target, role, &config)?;
            Ok(serde_json::json!({"role": role, "policy": policy}))
        })
        .collect::<Result<Vec<_>>>()?;
    if args.json {
        println!("{}", serde_json::to_string_pretty(&rows)?);
    } else {
        let lines = rows
            .iter()
            .map(|row| {
                let policy = &row["policy"];
                format!(
                    "{} · model={} · reasoning_effort={} · thinking_level={}",
                    row["role"].as_str().unwrap_or_default(),
                    policy["model"].as_str().unwrap_or("inherited"),
                    policy["reasoning_effort"].as_str().unwrap_or("inherited"),
                    policy["thinking_level"].as_str().unwrap_or("inherited")
                )
            })
            .collect();
        ui::print_dashboard(
            "Agent Policies",
            "effective overrides",
            &[],
            &[Section::new("Roles", lines)],
        )?;
    }
    Ok(())
}

fn reproject(
    scope: InstallScope,
    target: TargetRuntime,
    registry: &TemplateRegistry,
) -> Result<()> {
    let options = InstallOptions {
        action: InstallAction::Sync,
        scope,
        target,
        locale: None,
        dry_run: false,
        force: false,
        trust_project: false,
        json: false,
    };
    let result = Planner::new(registry, options).execute()?;
    if !result.summary.conflicts.is_empty() {
        bail!("agent policy changed but runtime projection has unmanaged file conflicts")
    }
    Ok(())
}

fn selected_roles(
    requested: &[String],
    all: bool,
    registry: &TemplateRegistry,
) -> Result<Vec<String>> {
    let known = registry
        .agents()
        .into_iter()
        .map(|agent| agent.name.clone())
        .collect::<Vec<_>>();
    let roles = if all {
        known.clone()
    } else {
        requested.to_vec()
    };
    if roles.is_empty() {
        bail!("select at least one --role or use --all")
    }
    for role in &roles {
        if !known.iter().any(|known_role| known_role == role) {
            bail!("unknown Megara role: {role}")
        }
    }
    Ok(roles)
}

fn print_change(
    action: &str,
    scope: InstallScope,
    target: TargetRuntime,
    roles: &[String],
    json: bool,
) -> Result<()> {
    if json {
        println!(
            "{}",
            serde_json::json!({"action": action, "scope": scope, "target": target, "roles": roles})
        );
    } else {
        ui::print_dashboard(
            "Agent Policies",
            action,
            &[],
            &[Section::new("Roles", roles.to_vec())],
        )?;
    }
    Ok(())
}

pub fn configure(
    scope: InstallScope,
    target: TargetRuntime,
    roles: &[String],
    policy: RolePolicy,
    force: bool,
) -> Result<()> {
    validate_policy(target, &policy)?;
    if roles.is_empty() {
        bail!("at least one role is required");
    }
    let path = config_path(scope)?;
    let content = read_writable_config(&path, force)?;
    let mut config: Value = strip_managed_marker(&content)
        .parse()
        .context("failed to parse Megara configuration")?;
    let root = config
        .as_table_mut()
        .context("Megara configuration must be a TOML table")?;
    let target_table = root
        .entry("target")
        .or_insert_with(|| Value::Table(Default::default()))
        .as_table_mut()
        .context("target must be a TOML table")?;
    let runtime_table = target_table
        .entry(target.to_string())
        .or_insert_with(|| Value::Table(Default::default()))
        .as_table_mut()
        .context("target runtime must be a TOML table")?;
    let roles_table = runtime_table
        .entry("roles")
        .or_insert_with(|| Value::Table(Default::default()))
        .as_table_mut()
        .context("target roles must be a TOML table")?;
    for role in roles {
        let role_table = roles_table
            .entry(role.clone())
            .or_insert_with(|| Value::Table(Default::default()))
            .as_table_mut()
            .context("role policy must be a TOML table")?;
        set_optional(role_table, "model", policy.model.as_deref());
        set_optional(
            role_table,
            "reasoning_effort",
            policy.reasoning_effort.as_deref(),
        );
        set_optional(
            role_table,
            "thinking_level",
            policy.thinking_level.as_deref(),
        );
    }
    fs::write(
        &path,
        format!("{CONFIG_MARKER}{}", toml::to_string_pretty(&config)?),
    )
    .with_context(|| format!("failed to write {}", path.display()))?;
    Ok(())
}

pub fn reset(
    scope: InstallScope,
    target: TargetRuntime,
    roles: &[String],
    force: bool,
) -> Result<()> {
    let path = config_path(scope)?;
    let content = read_writable_config(&path, force)?;
    let mut config: Value = strip_managed_marker(&content)
        .parse()
        .context("failed to parse Megara configuration")?;
    let Some(roles_table) = config
        .get_mut("target")
        .and_then(Value::as_table_mut)
        .and_then(|target_table| target_table.get_mut(&target.to_string()))
        .and_then(Value::as_table_mut)
        .and_then(|runtime| runtime.get_mut("roles"))
        .and_then(Value::as_table_mut)
    else {
        return Ok(());
    };
    for role in roles {
        roles_table.remove(role);
    }
    fs::write(
        &path,
        format!("{CONFIG_MARKER}{}", toml::to_string_pretty(&config)?),
    )
    .with_context(|| format!("failed to write {}", path.display()))?;
    Ok(())
}

fn read_config(scope: InstallScope) -> Result<Option<String>> {
    let path = config_path(scope)?;
    if !path.exists() {
        return Ok(None);
    }
    Ok(Some(strip_managed_marker(&fs::read_to_string(path)?)))
}

fn read_writable_config(path: &std::path::Path, force: bool) -> Result<String> {
    let content = fs::read_to_string(path).with_context(|| {
        format!(
            "Megara harness is not installed at {}; run megara install first",
            path.display()
        )
    })?;
    if !force && !content.contains(crate::installer::MANAGED_MARKER) {
        bail!(
            "refusing to overwrite unmanaged Megara configuration {}; rerun with --force to replace it",
            path.display()
        );
    }
    Ok(content)
}

fn policy_from_config(content: &str, target: TargetRuntime, role: &str) -> Result<RolePolicy> {
    let config: Value = content
        .parse()
        .context("failed to parse Megara configuration")?;
    let policy = config
        .get("target")
        .and_then(Value::as_table)
        .and_then(|target_table| target_table.get(&target.to_string()))
        .and_then(Value::as_table)
        .and_then(|runtime| runtime.get("roles"))
        .and_then(Value::as_table)
        .and_then(|roles| roles.get(role))
        .cloned()
        .unwrap_or_else(|| Value::Table(Default::default()));
    policy.try_into().context("role policy must be valid TOML")
}

fn validate_policy(target: TargetRuntime, policy: &RolePolicy) -> Result<()> {
    if policy
        .model
        .as_deref()
        .is_some_and(|value| value.trim().is_empty())
    {
        bail!("model must not be empty");
    }
    match target {
        TargetRuntime::Codex if policy.thinking_level.is_some() => {
            bail!("Codex uses reasoning_effort, not thinking_level")
        }
        TargetRuntime::Pi if policy.reasoning_effort.is_some() => {
            bail!("Pi uses thinking_level, not reasoning_effort")
        }
        TargetRuntime::Codex => {
            validate_level(policy.reasoning_effort.as_deref(), "reasoning_effort")
        }
        TargetRuntime::Pi => validate_level(policy.thinking_level.as_deref(), "thinking_level"),
    }
}

fn validate_level(value: Option<&str>, name: &str) -> Result<()> {
    let Some(value) = value else {
        return Ok(());
    };
    if matches!(value, "minimal" | "low" | "medium" | "high" | "xhigh") {
        Ok(())
    } else {
        bail!("{name} must be minimal, low, medium, high, or xhigh")
    }
}

fn set_optional(table: &mut toml::map::Map<String, Value>, key: &str, value: Option<&str>) {
    match value {
        Some(value) => table.insert(key.to_string(), Value::String(value.to_string())),
        None => table.remove(key),
    };
}
