use std::fs;

use crate::planning_artifact_support::{assert_ok, request, spec_proposal_for, ArtifactHarness};
use serde_json::json;
use sha2::{Digest, Sha256};

fn artifact_path(harness: &ArtifactHarness, name: &str) -> std::path::PathBuf {
    harness
        .directory
        .path()
        .join(".megara/planning/artifacts")
        .join(&harness.session_id)
        .join(name)
}

fn spec_request(
    harness: &mut ArtifactHarness,
    command_id: &str,
    force: bool,
) -> crate::planning::protocol::LogicalRequest {
    let state = harness.status_state();
    let work = state["required_model_action"].clone();
    let proposal = spec_proposal_for(&state, &work);
    request(
        "planning.spec.generate",
        command_id,
        Some(&harness.session_id),
        Some(state["revision"].as_u64().unwrap()),
        json!({"proposal":proposal,"projection_policy":{"force":force}}),
    )
}

#[test]
fn markdown_projection_has_exact_header_and_traceable_body() {
    let mut harness = ArtifactHarness::new();
    let request = spec_request(&mut harness, "cmd-projection-markdown", false);
    let response = harness.service.handle_request(request);
    assert_ok(&response);
    let path = artifact_path(&harness, "spec.md");
    let markdown = fs::read_to_string(path).unwrap();
    assert!(
        markdown.starts_with("<!--\nGenerated by Megara Planning Core.\nDo not edit directly.\n")
    );
    for field in [
        "session_id:",
        "candidate_id:",
        "semantic_hash:",
        "base_revision:",
    ] {
        assert_eq!(markdown.matches(field).count(), 1, "field={field}");
    }
    assert!(markdown.contains("- summary: A traceable canonical specification"));
    assert!(!markdown.contains("\\n"));
    assert_eq!(response["observed"]["projection_status"], "written");
}

#[test]
fn managed_projection_updates_but_direct_edit_conflicts_and_force_replay_repairs() {
    let mut harness = ArtifactHarness::new();
    let first_request = spec_request(&mut harness, "cmd-projection-replay", false);
    let first = harness.service.handle_request(first_request.clone());
    assert_ok(&first);
    let path = artifact_path(&harness, "spec.md");
    let original = fs::read_to_string(&path).unwrap();
    let manifest: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(artifact_path(&harness, "projection-manifest.json")).unwrap(),
    )
    .unwrap();
    let candidate = first["result"]["candidate"].clone();
    assert_eq!(
        manifest["files"]["spec"]["candidate_id"],
        candidate["candidate_id"]
    );
    assert_eq!(
        manifest["files"]["spec"]["semantic_hash"],
        candidate["semantic_hash"]
    );
    assert_eq!(
        manifest["files"]["spec"]["digest"],
        digest(original.as_bytes())
    );

    fs::write(&path, "user edit\n").unwrap();
    let conflict = harness.service.handle_request(first_request.clone());
    assert_ok(&conflict);
    assert_eq!(conflict["replayed"], true);
    assert_eq!(conflict["observed"]["projection_status"], "conflict");
    assert!(conflict["observed"]["warnings"]
        .as_array()
        .unwrap()
        .iter()
        .any(|warning| warning == "PROJECTION_CONFLICT"));
    assert_eq!(fs::read_to_string(&path).unwrap(), "user edit\n");
    assert_eq!(harness.status_state()["revision"], first["revision"]);

    let mut force_request = first_request;
    if let Some(params) = force_request.params.as_mut() {
        params["projection_policy"]["force"] = json!(true);
    }
    let repaired = harness.service.handle_request(force_request);
    assert_ok(&repaired);
    assert_eq!(repaired["replayed"], true);
    assert_eq!(repaired["observed"]["projection_status"], "written");
    assert_eq!(fs::read_to_string(&path).unwrap(), original);
}

#[test]
fn deleted_projection_is_recreated_from_cached_candidate_without_new_event() {
    let mut harness = ArtifactHarness::new();
    let request = spec_request(&mut harness, "cmd-projection-delete", false);
    let first = harness.service.handle_request(request.clone());
    assert_ok(&first);
    let path = artifact_path(&harness, "spec.md");
    fs::remove_file(&path).unwrap();
    let replay = harness.service.handle_request(request);
    assert_ok(&replay);
    assert_eq!(replay["replayed"], true);
    assert_eq!(replay["observed"]["projection_status"], "written");
    assert!(path.is_file());
    assert_eq!(harness.status_state()["revision"], first["revision"]);
}

#[test]
fn projection_io_warning_does_not_hide_committed_candidate() {
    let mut harness = ArtifactHarness::new();
    let directory = artifact_path(&harness, "");
    fs::create_dir_all(&directory).unwrap();
    fs::create_dir(directory.join("spec.md")).unwrap();
    let request = spec_request(&mut harness, "cmd-projection-io", false);
    let response = harness.service.handle_request(request);
    assert_ok(&response);
    assert_eq!(response["observed"]["projection_status"], "io_error");
    assert!(response["observed"]["warnings"]
        .as_array()
        .unwrap()
        .iter()
        .any(|warning| warning == "PROJECTION_IO"));
    assert!(response["result"]["state"]["spec"]["current_candidate"].is_object());
    let state = harness.status_state();
    assert!(state["spec"]["current_candidate"].is_object());
    let residue = fs::read_dir(directory)
        .unwrap()
        .map(|entry| entry.unwrap().file_name().to_string_lossy().to_string())
        .filter(|name| name.starts_with(".spec.md.tmp-"))
        .collect::<Vec<_>>();
    assert!(
        residue.is_empty(),
        "temporary projection residue: {residue:?}"
    );
}

#[test]
fn managed_old_candidate_is_overwritten_by_a_new_candidate() {
    let mut harness = ArtifactHarness::new();
    let first_request = spec_request(&mut harness, "cmd-projection-old", false);
    let first = harness.service.handle_request(first_request);
    assert_ok(&first);
    let path = artifact_path(&harness, "spec.md");
    let old = fs::read_to_string(&path).unwrap();
    let first_state = harness.status_state();
    let candidate_id = first_state["spec"]["current_candidate"]["candidate_id"]
        .as_str()
        .unwrap()
        .to_string();
    let revised = harness.service.handle_user_request(request(
        "planning.spec.revise",
        "cmd-projection-revise",
        Some(&harness.session_id),
        Some(first["revision"].as_u64().unwrap()),
        json!({"candidate_id":candidate_id,"text":"make the summary more precise"}),
    ));
    assert_ok(&revised);
    let state = harness.status_state();
    let work = state["required_model_action"].clone();
    let delta = harness.service.handle_request(request(
        "planning.audit.apply",
        "cmd-projection-redelta",
        Some(&harness.session_id),
        Some(state["revision"].as_u64().unwrap()),
        json!({
            "mode":"delta",
            "proposal":{
                "schema":"megara.audit-proposal/v1","mode":"delta",
                "work_item_id":work["work_item_id"],"base_revision":work["base_revision"],
                "base_domain_revision":work["base_domain_revision"],"input_hash":work["input_hash"],
                "readiness":"request_full_audit","next_question":null,"entity_ops":[],"edge_ops":[],
                "blocker_ops":[],"counterexample_review":null
            }
        }),
    ));
    assert_ok(&delta);
    let full_work = delta["result"]["state"]["required_model_action"].clone();
    let full = harness.service.handle_request(request(
        "planning.audit.apply",
        "cmd-projection-refull",
        Some(&harness.session_id),
        Some(delta["revision"].as_u64().unwrap()),
        json!({
            "mode":"full",
            "proposal":{
                "schema":"megara.audit-proposal/v1","mode":"full",
                "work_item_id":full_work["work_item_id"],"base_revision":full_work["base_revision"],
                "base_domain_revision":full_work["base_domain_revision"],"input_hash":full_work["input_hash"],
                "readiness":"ready","next_question":null,"entity_ops":[],"edge_ops":[],"blocker_ops":[],
                "counterexample_review":{"performed":true,"challenged_entity_ids":[],"findings":[]}
            }
        }),
    ));
    assert_ok(&full);
    let state = harness.status_state();
    let work = state["required_model_action"].clone();
    let mut proposal = spec_proposal_for(&state, &work);
    proposal["title"] = json!("Updated artifact specification");
    let second = harness.service.handle_request(request(
        "planning.spec.generate",
        "cmd-projection-new",
        Some(&harness.session_id),
        Some(state["revision"].as_u64().unwrap()),
        json!({"proposal":proposal,"projection_policy":{"force":false}}),
    ));
    assert_ok(&second);
    assert_eq!(second["observed"]["projection_status"], "written");
    let new = fs::read_to_string(path).unwrap();
    assert_ne!(new, old);
    assert!(new.contains("Updated artifact specification"));
    let manifest: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(artifact_path(&harness, "projection-manifest.json")).unwrap(),
    )
    .unwrap();
    let candidate = second["result"]["candidate"].clone();
    assert_eq!(
        manifest["files"]["spec"]["candidate_id"],
        candidate["candidate_id"]
    );
    assert_eq!(
        manifest["files"]["spec"]["semantic_hash"],
        candidate["semantic_hash"]
    );
    assert_eq!(manifest["files"]["spec"]["digest"], digest(new.as_bytes()));
}

#[test]
fn unmanaged_existing_projection_without_manifest_is_protected() {
    let mut harness = ArtifactHarness::new();
    let path = artifact_path(&harness, "spec.md");
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(&path, "unmanaged\n").unwrap();
    let request = spec_request(&mut harness, "cmd-projection-unmanaged", false);
    let response = harness.service.handle_request(request);
    assert_ok(&response);
    assert_eq!(response["observed"]["projection_status"], "conflict");
    assert_eq!(fs::read_to_string(path).unwrap(), "unmanaged\n");
}

#[test]
fn malformed_projection_manifest_is_a_warning_without_panic_or_orphan_artifact() {
    let mut harness = ArtifactHarness::new();
    let manifest_path = artifact_path(&harness, "projection-manifest.json");
    let candidate_path = artifact_path(&harness, "spec.md");
    fs::create_dir_all(manifest_path.parent().unwrap()).unwrap();
    fs::write(
        &manifest_path,
        serde_json::to_vec(&serde_json::json!({
            "schema":"megara.projection-manifest/v1",
            "session_id":harness.session_id,
            "files":"corrupt"
        }))
        .unwrap(),
    )
    .unwrap();
    let request = spec_request(&mut harness, "cmd-projection-malformed-manifest", false);
    let response = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        harness.service.handle_request(request)
    }))
    .expect("malformed manifest must not panic");
    assert_ok(&response);
    assert_eq!(response["observed"]["projection_status"], "io_error");
    assert!(response["result"]["state"]["spec"]["current_candidate"].is_object());
    assert!(!candidate_path.exists());
    let manifest: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(manifest_path).unwrap()).unwrap();
    assert_eq!(manifest["files"], "corrupt");
}

fn digest(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    format!("sha256:{:x}", hasher.finalize())
}
