use super::*;
use tempfile::tempdir;

#[test]
fn protects_unmanaged_files_without_force() {
    let dir = tempdir().unwrap();
    let path = dir.path().join("AGENTS.md");
    fs::write(&path, "manual").unwrap();

    let file = PlannedFile::new(path.clone(), "generated");
    let summary = write_files(&[file], true, false).unwrap();

    assert_eq!(summary.conflicts, vec![path]);
}

#[test]
fn conflicts_do_not_partially_write() {
    let dir = tempdir().unwrap();
    let conflict = dir.path().join("AGENTS.md");
    let created = dir.path().join("new.md");
    fs::write(&conflict, "manual").unwrap();

    let files = vec![
        PlannedFile::new(conflict, "generated"),
        PlannedFile::new(created.clone(), "generated"),
    ];
    let err = write_files(&files, false, false).unwrap_err();

    assert!(err.to_string().contains("refusing to overwrite"));
    assert!(!created.exists());
}

#[test]
fn force_updates_unmanaged_files() {
    let dir = tempdir().unwrap();
    let path = dir.path().join("AGENTS.md");
    fs::write(&path, "manual").unwrap();

    let file = PlannedFile::new(path.clone(), "generated");
    let summary = write_files(&[file], false, true).unwrap();

    assert_eq!(summary.updated, vec![path.clone()]);
    assert!(fs::read_to_string(path).unwrap().contains(MANAGED_MARKER));
}

#[test]
fn uses_language_comments_for_tool_support_files() {
    let dir = tempdir().unwrap();
    let python = PlannedFile::new(dir.path().join("engine/__main__.py"), "print('ok')\n");
    let javascript = PlannedFile::new(dir.path().join("engine/run.js"), "console.log('ok')\n");
    let yaml = PlannedFile::new(
        dir.path().join("engine/waf_profiles.yaml"),
        "profiles: []\n",
    );
    let requirements = PlannedFile::new(dir.path().join("requirements.txt"), "curl_cffi\n");

    write_files(&[python, javascript, yaml, requirements], false, false).unwrap();

    let python = fs::read_to_string(dir.path().join("engine/__main__.py")).unwrap();
    let javascript = fs::read_to_string(dir.path().join("engine/run.js")).unwrap();
    let yaml = fs::read_to_string(dir.path().join("engine/waf_profiles.yaml")).unwrap();
    let requirements = fs::read_to_string(dir.path().join("requirements.txt")).unwrap();
    assert!(python.starts_with("# MEGARA:MANAGED"));
    assert!(javascript.starts_with("// MEGARA:MANAGED"));
    assert!(yaml.starts_with("# MEGARA:MANAGED"));
    assert!(requirements.starts_with("# MEGARA:MANAGED"));
    assert!(!python.contains("<!-- MEGARA:MANAGED"));
    assert!(!javascript.contains("<!-- MEGARA:MANAGED"));
    assert!(!yaml.contains("<!-- MEGARA:MANAGED"));
    assert!(!requirements.contains("<!-- MEGARA:MANAGED"));
}

#[cfg(unix)]
#[test]
fn writes_executable_shell_files() {
    use std::os::unix::fs::PermissionsExt;

    let dir = tempdir().unwrap();
    let path = dir.path().join("bin/megara");
    let file = PlannedFile::new_executable_shell(path.clone(), "#!/bin/sh\nexit 0\n");

    let summary = write_files(&[file], false, false).unwrap();

    assert_eq!(summary.created, vec![path.clone()]);
    let mode = fs::metadata(path).unwrap().permissions().mode();
    assert_ne!(mode & 0o111, 0);
}

#[test]
fn removes_only_managed_files() {
    let dir = tempdir().unwrap();
    let managed = dir.path().join("managed.md");
    let unmanaged = dir.path().join("manual.md");
    fs::write(
        &managed,
        "<!-- MEGARA:MANAGED generated by Megara. -->\nold",
    )
    .unwrap();
    fs::write(&unmanaged, "manual").unwrap();

    let removed = remove_managed_files(&[managed.clone(), unmanaged.clone()], false).unwrap();

    assert_eq!(removed, vec![managed.clone()]);
    assert!(!managed.exists());
    assert!(unmanaged.exists());
}
