use super::*;

#[cfg(unix)]
#[test]
fn update_refreshes_project_harness_and_removes_legacy_codex_skills() {
    use std::os::unix::fs::PermissionsExt;

    let dir = tempdir().unwrap();
    let home = tempdir().unwrap();
    let codex_home = tempdir().unwrap();
    let fake_bin = tempdir().unwrap();
    let legacy_skill = dir.path().join(".codex/skills/deep-interview/SKILL.md");

    install_project_harness(dir.path(), codex_home.path());
    fs::create_dir_all(legacy_skill.parent().unwrap()).unwrap();
    fs::write(
        &legacy_skill,
        "<!-- MEGARA:MANAGED generated by Megara. -->\nlegacy",
    )
    .unwrap();
    assert!(legacy_skill.exists());

    let curl = fake_bin.path().join("curl");
    fs::write(
        &curl,
        format!(
            "#!/bin/sh\nprintf '%s\\n' '{{\"tag_name\":\"v{}\"}}'\n",
            env!("CARGO_PKG_VERSION")
        ),
    )
    .unwrap();
    let mut permissions = fs::metadata(&curl).unwrap().permissions();
    permissions.set_mode(0o755);
    fs::set_permissions(&curl, permissions).unwrap();

    let path = format!(
        "{}:{}",
        fake_bin.path().display(),
        std::env::var("PATH").unwrap_or_default()
    );
    let output = megara_with_codex_home(codex_home.path())
        .arg("update")
        .arg("--scope")
        .arg("project")
        .arg("--target")
        .arg("codex")
        .env("HOME", home.path())
        .env("PATH", path)
        .current_dir(dir.path())
        .output()
        .unwrap();

    assert!(
        output.status.success(),
        "stderr={}",
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("Megara / Update"));
    assert!(stdout.contains("Megara binary is current"));
    assert!(stdout.contains("Refreshing harness: scope=project, target=codex"));
    assert!(stdout.contains("Megara update complete."));
    assert!(!legacy_skill.exists());
    assert!(dir
        .path()
        .join(".agents/skills/deep-interview/SKILL.md")
        .exists());
    assert!(dir.path().join(".agents/.gitignore").exists());
    assert!(dir.path().join(".megara/.gitignore").exists());
    assert!(dir
        .path()
        .join(".agents/tools/insane-search/TOOL.md")
        .exists());
    assert!(dir
        .path()
        .join(".agents/skills/insane-search/SKILL.md")
        .exists());
    assert!(dir.path().join(".agents/bin/insane-search").exists());
    let wrapper = fs::read_to_string(dir.path().join(".agents/bin/insane-search")).unwrap();
    assert!(wrapper.contains(r#"runtime_root="$root_dir/../.megara""#));
    assert!(wrapper.contains("state/tools/insane-search"));
    assert!(wrapper.contains("pip install -r"));
}
